name: Deploy to Heroku

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3
        
    # 2. Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'npm'
    
    # 3. Install dependencies
      - name: Install dependencies
        run: npm install
    
    # 4. Build all projects
      - name: Build all projects
        run: npx nx run-many --target=build --all --configuration=production
    
    # 5. Verify build output
      - name: Verify build folder contents
        run: ls -la dist/apps/ticket-trade-api
    
    # 6. Set up Heroku CLI
      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
    
    # 7. Login to Heroku
      - name: Login to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku auth:token
    
    # 8. Deploy the subfolder
      - name: Deploy subfolder to Heroku
        run: |
          git subtree split --prefix dist/apps/ticket-trade-api release | xargs -I {} git push heroku {}:main
