name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  # Testing API (NestJS)
  test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install Dependencies
        run: npm install
        working-directory: ./apps/ticket-trade-api
      - name: Run Tests (API)
        run: npm run test:e2e
        working-directory: ./apps/ticket-trade-api

  # Testing Angular (Front-end)
  test-angular:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install Dependencies
        run: npm install
        working-directory: ./apps/ticket-trade-app
      - name: Run Tests (Angular)
        run: npm run test:e2e
        working-directory: ./apps/ticket-trade-app

  # Deployment for API (NestJS) on Heroku
  deploy-api:
    runs-on: ubuntu-latest
    needs: test-api
    steps:
      - uses: actions/checkout@v2
      - name: Setup Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
      - name: Authenticate with Heroku
        run: heroku auth:token
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      - name: Deploy to Heroku
        run: |
          heroku git:remote -a ticket-trade-api
          git push heroku main
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

  # Deployment for Angular on Vercel
  deploy-angular:
    runs-on: ubuntu-latest
    needs: test-angular
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install -g vercel
      - name: Deploy to Vercel
        run: vercel --prod
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}