name: Build, Test and Deploy

on:
  push:
    branches:
      - release

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    steps:
    # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3
        
    # 2. Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'npm'
    
    # 3. Install dependencies
      - name: Install dependencies
        run: npm install
    
    # 4. Build front-end and back-end
      - name: Build projects
        run: npx nx run-many --target=build --all --configuration=production
        
    # 5. Test front-end and back-end
      - name: Test projects
        run: npx nx run-many --target=test --all
    
    # 6. Prepare Heroku Deployment
      - name: Prepare Heroku Deployment
        run: |
          cd dist/apps/ticket-trade-api
          echo "web: node main.js" > Procfile

    # 7. Set up Heroku CLI
      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
    
    # 8. Deploy to Heroku
      - name: Deploy to Heroku
        run: |
          cd dist/apps/ticket-trade-api
          git init
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
          git add .
          git commit -m "Deploying to Heroku"
          git push --force heroku master
   
    # 9. Deploy to Vercel
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: dist/apps/ticket-trade-app
    
  e2e-tests:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install test dependencies
        run: npm install
        
      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run E2E tests on production site
        env:
          BASE_URL: ${{ secrets.FRONTEND_PRODUCTION_URL }}
        run: npx nx e2e ticket-trade-app-e2e